name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test_framework:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Notify about successful build and test step
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
          severity: info
          color: "#22BB33"
          text: Build and Test step for API Automation Framework is successful :), after latest commit by ${{ github.event.head_commit.author.username }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify about unsuccessful build and test step
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          severity: error
          text: Build for API Automation Framework Failed :<
          color: "#BB2124"
          details: https://github.com/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.event.head_commit.author.username }} broke the build :(
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
